name: Build & Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write # Allows the action to push to the repository (create/update gh-pages branch)
  pages: write    # Allows the action to trigger a Pages deployment (modern method)
  id-token: write # Required for deployment via the new GitHub Pages Action


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.4'

      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release --base-href "/flutter_alarm_app/"

      # ➡️ ADD THIS STEP ⬅️
      - name: Create .nojekyll file to disable Jekyll processing
        run: touch build/web/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
